gitops:
  manifest_projects:
    - ref:
        branch: review-env
      id: examples/gitlab-ci-cd/gitlab-devsecops-springboot3-maven
      paths:
        - glob: '*.yaml'
      default_namespace: default
      reconcile_timeout: 3600s
      dry_run_strategy: none
      prune: true
      prune_timeout: 3600s
      prune_propagation_policy: foreground
      inventory_policy: must_match